"""Read and write cached dense embedding artifacts for trainer samples."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any

import numpy as np

from trainer.dataset.schema import SupervisedSample
from trainer.io.dataset_reader import read_json


@dataclass(slots=True)
class CachedEmbeddingStore:
    """In-memory view of a saved embedding matrix and sample ordering."""

    matrix: np.ndarray[Any, Any]
    sample_ids: list[str]

    def select(self, samples: list[SupervisedSample]) -> np.ndarray[Any, Any]:
        """Return rows matching the requested sample ids in sample order."""

        index = {sample_id: position for position, sample_id in enumerate(self.sample_ids)}
        missing = [sample.sample_id for sample in samples if sample.sample_id not in index]
        if missing:
            raise KeyError(f"Missing cached embeddings for sample ids: {missing[:3]}")
        rows = [index[sample.sample_id] for sample in samples]
        return np.asarray(self.matrix[rows], dtype=np.float32)


def load_embedding_store(manifest_path: Path) -> CachedEmbeddingStore:
    """Load an embedding store from a manifest JSON path."""

    manifest = read_json(manifest_path)
    matrix_path = Path(str(manifest["matrix_path"]))
    if not matrix_path.is_absolute():
        matrix_path = manifest_path.parent / matrix_path
    payload = np.load(matrix_path, allow_pickle=False)
    matrix = np.asarray(payload["embeddings"], dtype=np.float32)
    sample_ids = [str(value) for value in payload["sample_ids"].tolist()]
    if matrix.shape[0] != len(sample_ids):
        raise ValueError(f"Embedding matrix row count {matrix.shape[0]} does not match {len(sample_ids)} sample ids")
    return CachedEmbeddingStore(matrix=matrix, sample_ids=sample_ids)


class CachedEmbeddingEncoder:
    """Embedding encoder facade backed by a precomputed artifact."""

    def __init__(self, manifest_path: Path) -> None:
        """Create a cached encoder from a manifest path.

        Args:
            manifest_path: Path to the embedding manifest generated by `build-embeddings`.
        """

        self.manifest_path = manifest_path
        self._store: CachedEmbeddingStore | None = None

    def _load(self) -> CachedEmbeddingStore:
        """Load the cached matrix once and reuse it for later predictions."""

        if self._store is None:
            self._store = load_embedding_store(self.manifest_path)
        return self._store

    def encode(self, samples: list[SupervisedSample]) -> np.ndarray[Any, Any]:
        """Return cached embeddings for samples in the requested order."""

        return self._load().select(samples)

    def __getstate__(self) -> dict[str, Any]:
        """Serialize only the manifest path, not the matrix cache."""

        return {"manifest_path": self.manifest_path, "_store": None}

    def __setstate__(self, state: dict[str, Any]) -> None:
        """Restore the cached encoder with lazy matrix loading."""

        self.manifest_path = state["manifest_path"]
        self._store = None
